In [4]:
#Array creation
import numpy as np
x = np.arange(30)
y = np.arange(35)
print(x)
print(y)
z = np.arange(25).reshape(5,5)
z

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
#Accessing meta data of an array
print(z.ndim)
print(type(z))
print(z.shape)
print(z.dtype)
print(z.size)
print(z.itemsize)

2
<class 'numpy.ndarray'>
(5, 5)
int64
25
8


In [6]:
#Creating arrays from lists
l = np.array([10,11,12,13,14,15])
print(type(l))
print(l.ndim)
print(l.shape)
print(l.size)

<class 'numpy.ndarray'>
1
(6,)
6


In [11]:
#Using eye(), linspace() and logspace() functions
m = np.eye(12)
dtype = np.float64
print(m)
n = np.linspace(1,8,19,endpoint=True)
print(n)
o = np.logspace(1,8,19,endpoint=True,base=10)
print(o)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[1.         1.38888889 1.77777778 2.16666667 2.55555556 2.94444444
 3.33333333 3.72222222 4.11111111 4.5        4.88888889 5.27777778
 5.66666667 6.05555556 6.44444444 6.83333333 7.22222222 7.61111111
 8.        ]
[1.00000000e+01 2.44843675e+01 5.99484250e+01 1.46779927e+02
 3.59381366e+02 8.79922544e+02 2.15443469e+03 5.27499706e+03
 1.29154967e+04 3.16227766e+04 7.74263683e+04 1.89573565e+05
 4.64158883e+05 1.13646367e+06 2.78255940e+06 6.81292069e+06
 1.66810054e+07 4.08423865e+07 1.00000000e+08]


In [13]:
#Using lambda function yo initialize arrays
p = np.fromfunction(lambda x,y:x==y, (3,3), dtype=float)
p

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [21]:
#Array operations
q = np.arange(24).reshape(6,4)
print(q)
print(q+1)
print(q*3)
r = q*q
print(r)
s = q.transpose()
print(r@s)#matrix multiplication

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]
 [36 39 42 45]
 [48 51 54 57]
 [60 63 66 69]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]
 [400 441 484 529]]
[[   36    92   148   204   260   316]
 [  244   748  1252  1756  2260  2764]
 [  644  2108  3572  5036  6500  7964]
 [ 1236  4172  7108 10044 12980 15916]
 [ 2020  6940 11860 16780 21700 26620]
 [ 2996 10412 17828 25244 32660 40076]]


In [32]:
#Performing operations on axis and using extreme fumctions
t = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(t)
print(t.sum(axis=1))
print(t.sum(axis=0))
print(t.sum())
print(t.min(),t.max())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]
[12 15 18]
45
1 9


In [40]:
#Universal Functions
u = t*np.pi/6.0
print(u)
v = np.tan(u)
print(v)
w = v-u
w

[[0.52359878 1.04719755 1.57079633]
 [2.0943951  2.61799388 3.14159265]
 [3.66519143 4.1887902  4.71238898]]
[[ 5.77350269e-01  1.73205081e+00  1.63312394e+16]
 [-1.73205081e+00 -5.77350269e-01 -1.22464680e-16]
 [ 5.77350269e-01  1.73205081e+00  5.44374645e+15]]


array([[ 5.37514936e-02,  6.84853256e-01,  1.63312394e+16],
       [-3.82644591e+00, -3.19534415e+00, -3.14159265e+00],
       [-3.08784116e+00, -2.45673940e+00,  5.44374645e+15]])

In [53]:
#Array slicing
ar = np.arange(4)
print(ar)
print(ar[2])
print(ar[0:3])
print(ar[:2])

[0 1 2 3]
2
[0 1 2]
[0 1]


In [73]:
#Multidimensional array
arr = np.arange(24).reshape(4,6)
print(arr)
print(arr[3,2])
print(arr[3:])
print(arr[:,1:3])
print(arr[1:5,:])
arrr = arr.flatten()
print(arrr)
for i in arrr:
    print(i)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
20
[[18 19 20 21 22 23]]
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]]
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [78]:
#Copying arrays
#Referencing
road = np.arange(4)
print(road)
street = road
print(street)
print(road is street)
street.shape = (2,2)
print(street)
road.shape

[0 1 2 3]
[0 1 2 3]
True
[[0 1]
 [2 3]]


(2, 2)

In [80]:
#Shallow copying
road1 = np.arange(12).reshape(2,6)
print(road1)
highway = road1[:]
print(highway)
print(highway is road)
highway.shape = (3,4)
print(highway)
road1.shape

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
False
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(2, 6)

In [81]:
#Checking arrays
print(highway is road)
print(highway.base is road)
print(highway.flags.owndata)
print(road.flags.owndata)

False
False
False
True


In [82]:
#Deep copy
airport = road.copy()
airport[:] = 0.0
print(road)
airport


[[0 1]
 [2 3]]


array([[0, 0],
       [0, 0]])