In [ ]:
#Boolean indexing
import numpy as np
ar = np.arange(40).reshape(5,8)
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
#Accessing specific elements
print(ar[ar>12])
print(ar[ar<4])
print(ar[::-1])
print(ar[4:5,1])
print(ar[1:3,2:4])
print(ar[3,5])

[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
 37 38 39]
[0 1 2 3]
[[32 33 34 35 36 37 38 39]
 [24 25 26 27 28 29 30 31]
 [16 17 18 19 20 21 22 23]
 [ 8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7]]
[33]
[[10 11]
 [18 19]]
29


In [ ]:
#Altering using indexing
ar[ar > 12] = 4
print(ar)


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12  4  4  4]
 [ 4  4  4  4  4  4  4  4]
 [ 4  4  4  4  4  4  4  4]
 [ 4  4  4  4  4  4  4  4]]


In [ ]:
#Reinitialising array
ar[ar>3] = 0
ar

array([[0, 1, 2, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
#Using two tests on the array
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14]).reshape(7,2)
print(c)
c[np.logical_or(c>6,c>15)] = 1
print(c)
c>1

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]
[[1 2]
 [3 4]
 [5 6]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


array([[False,  True],
       [ True,  True],
       [ True,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [ ]:
#Avoiding loops 
x = 25
y = 27
xmin = ymin = 0
xmax = ymax = 1
a = np.linspace(xmin,xmax,x,endpoint=True)
b = np.linspace(ymin,ymax,y,endpoint = True)
print(a.shape)
print(b.shape)
print(a)
print(b)

(25,)
(27,)
[0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333
 1.        ]
[0.         0.03846154 0.07692308 0.11538462 0.15384615 0.19230769
 0.23076923 0.26923077 0.30769231 0.34615385 0.38461538 0.42307692
 0.46153846 0.5        0.53846154 0.57692308 0.61538462 0.65384615
 0.69230769 0.73076923 0.76923077 0.80769231 0.84615385 0.88461538
 0.92307692 0.96153846 1.        ]


In [ ]:
#Checking time elapsed
import time
t0 = time.time()
f = np.zeros((x,y))
for i in range(x):
    for j in range(y): 
        f[i,j] = np.cos(2.0*np.pi*a[i]*b[j])
t1= time.time()
"The time elapsed is {} seconds".format(t0-t1)


'The time elapsed is -0.0018496513366699219 seconds'

In [ ]:
#Using Mesh Grid
ar,br = np.meshgrid(a,b,indexing='ij')
print(ar[3:16,12])
print(br[:12,12])
t0 = time.time()
f2 = np.cos(2*np.pi*a[i]*b[i])
t1 = time.time()
"The time elapsed is {} seconds".format(t0-t1)



[0.125      0.16666667 0.20833333 0.25       0.29166667 0.33333333
 0.375      0.41666667 0.45833333 0.5        0.54166667 0.58333333
 0.625     ]
[0.46153846 0.46153846 0.46153846 0.46153846 0.46153846 0.46153846
 0.46153846 0.46153846 0.46153846 0.46153846 0.46153846 0.46153846]


'The time elapsed is -7.843971252441406e-05 seconds'

In [55]:
#Array concatenation 
me = np.arange(4)
you = np.arange(5)
others = np.array([6,9])
print(np.concatenate([me,you]))
np.concatenate([me,you,others])

[0 1 2 3 0 1 2 3 4]


array([0, 1, 2, 3, 0, 1, 2, 3, 4, 6, 9])

In [62]:
#Concatenating two dimensional array
hi = np.array([[1,2,3],
              [4,5,6],
               [7,8,9]])
hey = np.concatenate([hi,hi],axis=0)
print(hey)
hello = np.concatenate([hi,hi],axis=1)
hello

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [63]:
#Splitting arrays
yo = np.arange(15)
a,b,c,d = np.split(yo,(2,5,10))
print(a,b,c,d)

[0 1] [2 3 4] [5 6 7 8 9] [10 11 12 13 14]


In [66]:
#Splitting two dimensional array
bob = np.arange(36).reshape(6,6)
print(bob)
hi,bye = np.vsplit(bob,[4])
print(hi)
print(bye)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [68]:
#Aggregates
su = np.arange(1,5)
print(su)
s = np.add.reduce(su)
print(s)
u = np.multiply.reduce(su)
print(u)
l = np.add.accumulate(su)
print(l)
e = np.multiply.accumulate(su)
e

[1 2 3 4]
10
24
[ 1  3  6 10]


array([ 1,  2,  6, 24])